# This is a basic workflow to help you get started with Actions
name: "Build"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Initializing Cache
      id: npm-cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Checkout Repo
      uses: actions/checkout@v2
      
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Create Branch
      run: |
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git config user.name "${{ github.actor }}"

        git fetch
        git checkout master
        git reset --hard HEAD
        git checkout -b "build-${{ github.sha }}"

    - name: Extract Version
      id: extract-version
      run: |
        PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')

        echo "::set-output name=version::$PACKAGE_VERSION"
    
    # - name: Install Dependencies
    #   run: npm install

    # - name: Build Bundle
    #   run: npm run build

    - name: Commit Changes
      if: success()
      run: |
        cat > manifest.txt << EOF
        By: ${{ github.actor }}
        Commit: ${{ github.sha }}
        Version: ${{ steps.extract-version.outputs.version }}
        EOF

        echo $PACKAGE_VERSION

        git add -A

        git commit -a -m "Build: ${{ github.sha }}"
        git checkout master
        git merge "build-${{ github.sha }}"
        git push

    # - name: Publish to NPM
    #   run: npm publish --access public
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
